### ISSUE TITLE
Allow users to strip outgroups from tree

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki#20]
Sometimes you need to remove the outgroups used to anchor the tree, particularly for publication. Iroki could provide the option where the user defines the outgroup members that should be removed from the tree (one or more). Error if they provide a list that is polyphyletic (i.e. something that would change the topology of the tree instead of just trimming it).

**Comment by mooreryan** [comment]
For now, this is outside the scope of Iroki. But, since this would be a cool feature, I've added it to the `WISHLIST.md` file.
