### ISSUE TITLE
Problems with sequence numeric names starting with 0

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/iroki#64]
Likely a problem with the CSV parser considering the name to be a number and stripping the 0's from the start.

**Comment by mooreryan** [comment]
Did they display properly in the tree viewer when not using the mapping file?

**Comment by mooreryan** [comment]
Also, can you send me your mapping file?

**Comment by mooreryan** [comment]
This should be fixed by the referenced commit.

It's live on the website, but you should reload the page before trying it.
